// ─── Mock Data ────────────────────────────────────────────────────────────────
// Simulates a backend API. Replace with real fetch calls later.

export const TUTORIALS = [
  {
    id: '1',
    title: 'Fix a Cracked Phone Screen at Home',
    description: 'Step-by-step guide to replacing a cracked screen using basic tools. Works for most Android models.',
    category: 'Smartphones',
    duration: '18 min',
    views: 12400,
    rating: 4.8,
    thumbnail: 'https://picsum.photos/seed/tutorial1/400/220',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', // placeholder
    author: 'Marcus T.',
    tags: ['screen', 'android', 'repair'],
  },
  {
    id: '2',
    title: 'Laptop Overheating? Clean Your Fan',
    description: 'A dirty fan causes 80% of laptop slowdowns. Learn to safely clean it in under 20 minutes.',
    category: 'Laptops',
    duration: '22 min',
    views: 9800,
    rating: 4.7,
    thumbnail: 'https://picsum.photos/seed/tutorial2/400/220',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    author: 'Priya N.',
    tags: ['laptop', 'cooling', 'cleaning'],
  },
  {
    id: '3',
    title: 'Replace a MacBook Battery Yourself',
    description: 'Save $200+ by swapping your MacBook battery with a compatible unit. Includes safety tips.',
    category: 'Laptops',
    duration: '35 min',
    views: 7600,
    rating: 4.6,
    thumbnail: 'https://picsum.photos/seed/tutorial3/400/220',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    author: 'Jordan K.',
    tags: ['macbook', 'battery', 'apple'],
  },
  {
    id: '4',
    title: 'Wi-Fi Router Setup & Security Basics',
    description: 'Configure your router properly, change defaults, and protect your home network from intruders.',
    category: 'Networking',
    duration: '14 min',
    views: 15200,
    rating: 4.9,
    thumbnail: 'https://picsum.photos/seed/tutorial4/400/220',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    author: 'Sam L.',
    tags: ['wifi', 'router', 'security'],
  },
  {
    id: '5',
    title: 'Recover Deleted Files Without Software',
    description: 'Use built-in Windows and macOS tools to recover accidentally deleted documents and photos.',
    category: 'Software',
    duration: '10 min',
    views: 22100,
    rating: 4.5,
    thumbnail: 'https://picsum.photos/seed/tutorial5/400/220',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    author: 'Aisha R.',
    tags: ['data recovery', 'windows', 'mac'],
  },
  {
    id: '6',
    title: 'Upgrade Your RAM: Full Walkthrough',
    description: 'Double your PC performance for under $50. This guide covers desktops and compatible laptops.',
    category: 'Hardware',
    duration: '28 min',
    views: 8300,
    rating: 4.7,
    thumbnail: 'https://picsum.photos/seed/tutorial6/400/220',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    author: 'Dev P.',
    tags: ['ram', 'upgrade', 'pc'],
  },
];

export const TECHNICIANS = [
  {
    id: 't1',
    name: 'Marcus Thompson',
    specialty: 'Phone & Tablet Repair',
    skills: ['Screen replacement', 'Battery swap', 'Water damage'],
    rate: 45,
    availability: 'Mon–Fri, 9am–6pm',
    rating: 4.9,
    reviews: 138,
    distance: '0.4 mi',
    status: 'available', // available | busy | unavailable
    bio: 'Certified mobile repair tech with 7 years experience. Most fixes done same day.',
    avatar: 'https://i.pravatar.cc/100?img=12',
  },
  {
    id: 't2',
    name: 'Priya Nair',
    specialty: 'Laptop & MacBook Repair',
    skills: ['Logic board repair', 'SSD upgrades', 'OS reinstall'],
    rate: 60,
    availability: 'Tue–Sat, 10am–7pm',
    rating: 4.8,
    reviews: 92,
    distance: '0.9 mi',
    status: 'available',
    bio: 'Apple-certified technician. Specializes in MacBook Pro/Air. Remote support available.',
    avatar: 'https://i.pravatar.cc/100?img=47',
  },
  {
    id: 't3',
    name: 'Jordan Kim',
    specialty: 'PC Building & Upgrades',
    skills: ['Custom builds', 'RAM/GPU upgrades', 'Troubleshooting'],
    rate: 50,
    availability: 'Weekends, 11am–5pm',
    rating: 4.7,
    reviews: 67,
    distance: '1.2 mi',
    status: 'busy',
    bio: 'PC enthusiast and builder. Can source parts at competitive prices.',
    avatar: 'https://i.pravatar.cc/100?img=53',
  },
  {
    id: 't4',
    name: 'Sam Liu',
    specialty: 'Networking & Smart Home',
    skills: ['Router setup', 'Mesh networks', 'Smart home wiring'],
    rate: 55,
    availability: 'Mon, Wed, Fri, 8am–4pm',
    rating: 4.9,
    reviews: 204,
    distance: '1.8 mi',
    status: 'available',
    bio: 'Network engineer by day, community tech helper on weekends and off-days.',
    avatar: 'https://i.pravatar.cc/100?img=60',
  },
  {
    id: 't5',
    name: 'Aisha Robinson',
    specialty: 'Software & Data Recovery',
    skills: ['Virus removal', 'Data recovery', 'OS setup'],
    rate: 40,
    availability: 'Daily, 6pm–10pm',
    rating: 4.6,
    reviews: 51,
    distance: '2.1 mi',
    status: 'available',
    bio: 'CS grad helping neighbors with software issues. Evening slots only.',
    avatar: 'https://i.pravatar.cc/100?img=29',
  },
];

export const REPAIR_SHOPS = [
  {
    id: 's1',
    name: 'QuickFix Electronics',
    specialty: 'General Repair',
    rating: 4.7,
    reviews: 312,
    distance: '0.3 mi',
    hours: 'Open · Closes 8pm',
    address: '148 Flatbush Ave',
  },
  {
    id: 's2',
    name: 'Brooklyn Tech Hub',
    specialty: 'Phone & Laptop',
    rating: 4.9,
    reviews: 541,
    distance: '0.7 mi',
    hours: 'Open · Closes 7pm',
    address: '22 DeKalb Ave',
  },
  {
    id: 's3',
    name: 'iCare Repairs',
    specialty: 'Apple Products',
    rating: 4.5,
    reviews: 187,
    distance: '1.1 mi',
    hours: 'Open · Closes 6pm',
    address: '90 Fulton St',
  },
  {
    id: 's4',
    name: 'NerdForce Pro',
    specialty: 'Business IT & Home Setup',
    rating: 4.8,
    reviews: 220,
    distance: '1.6 mi',
    hours: 'Closed · Opens 9am',
    address: '5 Hanson Pl',
  },
];

// Mock recently viewed (simulates local storage / user session)
export const RECENTLY_VIEWED = [TUTORIALS[3], TUTORIALS[0], TUTORIALS[4]];
